// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 11, 16, 15, 9, 32, 914, DateTimeKind.Local).AddTicks(84),
                            Details = "My employer has been great to work for, and we have achieved many productive things whilst I have been working there.",
                            ImageUrl = "https://www.booking.com/hotel/ng/the-retreat-sangotedo.en-gb.html?aid=303948&label=sangotedo-apFnh3uy8KNx8xxrsqblXAS528791914267%3Apl%3Ata%3Ap12%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-233752489278%3Alp9073716%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9Yf5EcukO1MOGLSSAuId8ToA&sid=a106f137968291ceaec8484455dfcbbf&dest_id=-2026094&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1668543595&srpvid=88468ef42c9f027c&type=total&ucfs=1&activeTab=photosaGallery",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 11, 16, 15, 9, 32, 914, DateTimeKind.Local).AddTicks(96),
                            Details = "My strengths include learning new things quickly and completing all tasks as per the required brief. I am commercially/technically aware which means I understand my responsibilities in this ",
                            ImageUrl = "https://www.booking.com/hotel/ng/the-retreat-sangotedo.en-gb.html?aid=303948&label=sangotedo-apFnh3uy8KNx8xxrsqblXAS528791914267%3Apl%3Ata%3Ap12%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-233752489278%3Alp9073716%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9Yf5EcukO1MOGLSSAuId8ToA&sid=a106f137968291ceaec8484455dfcbbf&dest_id=-2026094&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1668543595&srpvid=88468ef42c9f027c&type=total&ucfs=1&activeTab=photosaGallery",
                            Name = "Blue Moon",
                            Occupancy = 30,
                            Rate = 300.0,
                            Sqft = 730,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 11, 16, 15, 9, 32, 914, DateTimeKind.Local).AddTicks(97),
                            Details = "I am great with people, I always put the needs of a team first and I will always take on duties that are outside the job description.",
                            ImageUrl = "https://www.booking.com/hotel/ng/the-retreat-sangotedo.en-gb.html?aid=303948&label=sangotedo-apFnh3uy8KNx8xxrsqblXAS528791914267%3Apl%3Ata%3Ap12%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-233752489278%3Alp9073716%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9Yf5EcukO1MOGLSSAuId8ToA&sid=a106f137968291ceaec8484455dfcbbf&dest_id=-2026094&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1668543595&srpvid=88468ef42c9f027c&type=total&ucfs=1&activeTab=photosaGallery",
                            Name = "Mosafuneto Villa",
                            Occupancy = 45,
                            Rate = 130.0,
                            Sqft = 213,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 11, 16, 15, 9, 32, 914, DateTimeKind.Local).AddTicks(98),
                            Details = "my biggest weakness is the fact that I find it hard to say no to people that need help. I tend to say yes to everything and I end up taking on too many responsibilities. I never let people down",
                            ImageUrl = "https://www.booking.com/hotel/ng/the-retreat-sangotedo.en-gb.html?aid=303948&label=sangotedo-apFnh3uy8KNx8xxrsqblXAS528791914267%3Apl%3Ata%3Ap12%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-233752489278%3Alp9073716%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9Yf5EcukO1MOGLSSAuId8ToA&sid=a106f137968291ceaec8484455dfcbbf&dest_id=-2026094&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1668543595&srpvid=88468ef42c9f027c&type=total&ucfs=1&activeTab=photosaGallery",
                            Name = "Diamond Villa",
                            Occupancy = 7,
                            Rate = 50.0,
                            Sqft = 100,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 11, 16, 15, 9, 32, 914, DateTimeKind.Local).AddTicks(99),
                            Details = "I would always try to resolve the conflict by myself as a mature and professional employee. I would always put the interest of the team first and I won’t include my manager unless absolutely necessary.",
                            ImageUrl = "https://www.booking.com/hotel/ng/the-retreat-sangotedo.en-gb.html?aid=303948&label=sangotedo-apFnh3uy8KNx8xxrsqblXAS528791914267%3Apl%3Ata%3Ap12%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-233752489278%3Alp9073716%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9Yf5EcukO1MOGLSSAuId8ToA&sid=a106f137968291ceaec8484455dfcbbf&dest_id=-2026094&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1668543595&srpvid=88468ef42c9f027c&type=total&ucfs=1&activeTab=photosaGallery",
                            Name = "Bethsida Hotel",
                            Occupancy = 32,
                            Rate = 70.0,
                            Sqft = 450,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
